require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CallHistoriesController do

  # This should return the minimal set of attributes required to create a valid
  # CallHistory. As you add validations to CallHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "phone_number" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CallHistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all call_histories as @call_histories" do
      call_history = CallHistory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:call_histories).should eq([call_history])
    end
  end

  describe "GET show" do
    it "assigns the requested call_history as @call_history" do
      call_history = CallHistory.create! valid_attributes
      get :show, {:id => call_history.to_param}, valid_session
      assigns(:call_history).should eq(call_history)
    end
  end

  describe "GET new" do
    it "assigns a new call_history as @call_history" do
      get :new, {}, valid_session
      assigns(:call_history).should be_a_new(CallHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested call_history as @call_history" do
      call_history = CallHistory.create! valid_attributes
      get :edit, {:id => call_history.to_param}, valid_session
      assigns(:call_history).should eq(call_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CallHistory" do
        expect {
          post :create, {:call_history => valid_attributes}, valid_session
        }.to change(CallHistory, :count).by(1)
      end

      it "assigns a newly created call_history as @call_history" do
        post :create, {:call_history => valid_attributes}, valid_session
        assigns(:call_history).should be_a(CallHistory)
        assigns(:call_history).should be_persisted
      end

      it "redirects to the created call_history" do
        post :create, {:call_history => valid_attributes}, valid_session
        response.should redirect_to(CallHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved call_history as @call_history" do
        # Trigger the behavior that occurs when invalid params are submitted
        CallHistory.any_instance.stub(:save).and_return(false)
        post :create, {:call_history => { "phone_number" => "invalid value" }}, valid_session
        assigns(:call_history).should be_a_new(CallHistory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CallHistory.any_instance.stub(:save).and_return(false)
        post :create, {:call_history => { "phone_number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested call_history" do
        call_history = CallHistory.create! valid_attributes
        # Assuming there are no other call_histories in the database, this
        # specifies that the CallHistory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CallHistory.any_instance.should_receive(:update).with({ "phone_number" => "MyString" })
        put :update, {:id => call_history.to_param, :call_history => { "phone_number" => "MyString" }}, valid_session
      end

      it "assigns the requested call_history as @call_history" do
        call_history = CallHistory.create! valid_attributes
        put :update, {:id => call_history.to_param, :call_history => valid_attributes}, valid_session
        assigns(:call_history).should eq(call_history)
      end

      it "redirects to the call_history" do
        call_history = CallHistory.create! valid_attributes
        put :update, {:id => call_history.to_param, :call_history => valid_attributes}, valid_session
        response.should redirect_to(call_history)
      end
    end

    describe "with invalid params" do
      it "assigns the call_history as @call_history" do
        call_history = CallHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CallHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => call_history.to_param, :call_history => { "phone_number" => "invalid value" }}, valid_session
        assigns(:call_history).should eq(call_history)
      end

      it "re-renders the 'edit' template" do
        call_history = CallHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CallHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => call_history.to_param, :call_history => { "phone_number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested call_history" do
      call_history = CallHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => call_history.to_param}, valid_session
      }.to change(CallHistory, :count).by(-1)
    end

    it "redirects to the call_histories list" do
      call_history = CallHistory.create! valid_attributes
      delete :destroy, {:id => call_history.to_param}, valid_session
      response.should redirect_to(call_histories_url)
    end
  end

end
